<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>NotepadClone</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotepadCloneLibrary\NotepadCloneLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Include="Properties\PublishProfiles\FolderProfile.pubxml">
      <IsPublishProfile>true</IsPublishProfile>
      </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
	
   <PropertyGroup>
	  <AssemblyName>NotepadClone</AssemblyName>
      <AssemblyTitle>Notepad Clone by Muhammad Magdi</AssemblyTitle>
	  <Product>Notepad Clone by Muhammad Magdi</Product>
	  <Description>A lightweight text editor for daily use.</Description>
	  <StartupObject>NotepadClone.Program</StartupObject>
   </PropertyGroup>

</Project>